export const ENGLISH_MOTIVATION = [
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Don't watch the clock; do what it does. Keep going.",
    "UPSC is not just an exam, it's a lifestyle.",
    "Arise, awake, and stop not till the goal is reached.",
    "Nothing is impossible. The word itself says 'I'm possible'!",
    "Dream big. Work hard. Stay humble.",
    "Believe you can and you're halfway there.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "The only way to do great work is to love what you do.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Tough times never last, but tough people do.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Opportunities don't happen, you create them."
];

export const HINDI_MOTIVATION = [
    "Mehnat itni khamoshi se karo ki safalta shor macha de.",
    "Sapne wo nahi jo sote waqt dekhe jaye, sapne wo hai jo sone na de.",
    "Koshish karne walon ki kabhi haar nahi hoti.",
    "Manzil unhi ko milti hai jinke sapno mein jaan hoti hai.",
    "Samay aur samajh ek saath khushkismat logon ko hi milte hain.",
    "Haar mat maano, shuruaat hamesha sabse kathin hoti hai.",
    "Jo apne kadmon ki kabiliyat par vishwas rakhte hain, wahi manzil par pahunchte hain.",
    "Sangarsh jitna kathin hoga, jeet utni hi shandaar hogi.",
    "Agar tum suraj ki tarah chamakna chahte ho, toh pehle suraj ki tarah jalna seekho.",
    "Waqt aapka hai, chaho toh sona bana lo ya sone mein guzaar do.",
    "Bina sangharsh ke koi mahan nahi banta.",
    "Lakshya na ojhal hone paaye, kadam mila kar chal.",
    "Utho, jaago aur tab tak mat ruko jab tak lakshya na mil jaye.",
    "Kathinaiyan wo cheezein hain jo humein tab dikhti hain jab hamara dhyaan lakshya se hat jaata hai.",
    "Jinmein akele chalne ke hounsle hote hain, ek din unhi ke peeche kafile hote hain.",
    "Sabr kar bande, musibat ke din bhi guzar jayenge, hansi udane walon ke chehre bhi utar jayenge.",
    "Nind se itna bhi pyaar na karo ki manzil bhi khwab ban jaye.",
    "Jeetne ka maza tabhi aata hai jab sab aapke haarne ka intezaar kar rahe ho.",
    "Abhi to asli manzil pana baaki hai, abhi to iradon ka imtihaan baaki hai.",
    "Apne sapno ko sanson mein rakho, har manzil ko apni bahon mein rakho."
];

export const PHOTO_COMPLIMENTS = [
    "Who needs a study break when you look this good? 😍",
    "Okay, now I'm distracted from my work... you look stunning! ❤️",
    "UPSC Syllabus: Important. You: Most Important. 💖",
    "Damn! That smile just made my day. ✨",
    "Officer in making? More like Queen in ruling! 👑",
    "Stop looking so cute, I need to focus on coding! 😉",
    "Is it hot in here or is it just you? 🔥",
    "My daily motivation just got a major upgrade. 🚀",
    "Confidence looks good on you, babe. 😘",
    "Looking sharp, future IAS Officer! 🇮🇳"
];
